#!/bin/bash

user=$(whoami)
repo=${PWD##*/}
current_branch=$(git rev-parse --abbrev-ref HEAD)

delete () {
    echo "Unlocking $repo for user $user"
    ssh git@git.xfce.org D unlock users/$user/$repo
    echo "Deleting the repository $repo"
    ssh git@git.xfce.org D rm users/$user/$repo
}

create () {
    echo "Adding remote 'private' to repo $repo for user $user"
    git remote add private ssh://git@git.xfce.org/users/$user/$repo
    git remote -v
}

fastforward () {
    echo "Fast-fowarding branch $current_branch in repo $repo"
    git push private :$current_branch ; git push private $current_branch
}

perms () {
    addremove=$1
    otheruser=$2
    if [ -n "$addremove" ]; then
        if [ -n "$otheruser" ]; then
            if [ "$addremove" == "+" ]; then
                echo "Granting write access to user $otheruser on repo $repo"
            elif [ "$addremove" == "-" ]; then
                echo "Removing write access from user $otheruser on repo $repo"
            else
                echo "Syntax error. Usage for granting permissions: 'perms +/- <username>'"
            fi
            ssh git@git.xfce.org perms users/$user/$repo $addremove WRITERS $otheruser
        else
            echo "Syntax error. Usage for granting permissions: 'perms +/- <username>'"
        fi
    fi
    echo "Current permissions for users/$user/$repo:"
    ssh git@git.xfce.org perms users/$user/$repo -l
}

grantaccess () {
    if [ -n "$1" ]; then
        perms "+" $1
    else
        echo "Syntax error. Expected a valid username as argument. (Usage: 'grantaccess <username>')"
    fi
}

# main loop
if [ -n "$1" ]; then
    if [ "$1" == "delete" ]; then
        delete
    elif [ "$1" == "create" ]; then
        create
    elif [ "$1" == "ff" ]; then
        fastforward
    elif [ "$1" == "grantaccess" ]; then
        grantaccess $2
    elif [ "$1" == "perms" ]; then
        perms $2 $3
    else
        echo "Error. Invalid argument."
        echo "Please use either 'create', 'delete', 'ff' (fast-forward), 'grantaccess' or 'perms' as arguments."
    fi
else
    echo "Error. This script expects an argument ('create', 'delete', 'ff' (fast-forward), 'grantaccess' or 'perms')."
fi
