#!/bin/bash

# Simple script to migrate the remotes of all git repositories below the current
# directory from git.xfce.org to gitlab.xfce.org

migrate_to_gl () {
  for d in */; do
      cd "$d"

      if git ls-files >& /dev/null; then
          if git remote -v | grep git.xfce.org >& /dev/null; then
              echo "* Updating git remotes in $d"
              sed -Ei '
                  s|git://|https://|
                  s|git\.xfce\.org(.*[^/])/?|gitlab.xfce.org\1.git|
              ' .git/config
              echo "  ✓ Done"
          fi
      fi

      cd ..
  done
}

read -n 1 -p "Do you want to migrate all Git repositories in the current folder from git.xfce.org to gitlab.xfce.org? ([y]es, [n]o)" response
printf "\n"
if [ "$response" = "y" ]; then
    migrate_to_gl
    printf "\nFinished.\n"
else
    printf "Aborted.\n"
    exit 0;
fi
